spring.application.name=mailservice


# ===============================
# MySQL
# ===============================
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/mailservice_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Settings (Connection Pool)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA / Hibernate Properties
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Storage
# ===============================
storage.upload-dir=uploads

# ===============================
# Workers
# ===============================
worker.csv.batch-size=500
worker.upload-job.delay-ms=2000
worker.outbox.delay-ms=1000
worker.outbox.batch-size=500
worker.email-sender.threads=10
worker.email-sender.queue=email_queue

# ===============================
# Email
# ===============================
email.default-subject=Welcome
email.default-body=Hello from the mail service
email.retry.max=3

# ===============================
# AWS SES
# ===============================
aws.region=us-east-1
aws.ses.source=your-verified-email@domain.com
